"""Migracion con atributo de activo en el modelo de usuario

Revision ID: 0cb897b47764
Revises: a13893d8d1bf
Create Date: 2026-05-04 04:14:42.842084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb897b47764'
down_revision: Union[str, Sequence[str], None] = 'a13893d8d1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('activo', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'activo')
    # ### end Alembic commands ###
