"""Tercera migracion de la BD

Revision ID: 4a3c69596be1
Revises: 354ac17ba672
Create Date: 2026-04-03 19:50:33.263483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3c69596be1'
down_revision: Union[str, Sequence[str], None] = '354ac17ba672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direccion', sa.Column('numero_telefonico', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direccion', 'numero_telefonico')
    # ### end Alembic commands ###
