"""Cuarta migracion de la BD

Revision ID: 5413b34c6f54
Revises: 
Create Date: 2026-04-06 23:33:40.860746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5413b34c6f54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('color_preferencia_hex', sa.String(length=10), nullable=False),
    sa.Column('tipo_categoria', sa.Enum('producto', 'servicio', name='tipocategoriaenum'), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('cliente', 'emprendedora', 'administrador', name='tipousuarioenum'), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('foto_perfil_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrito',
    sa.Column('id_carrito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_carrito'),
    sa.UniqueConstraint('id_cliente')
    )
    op.create_table('direccion',
    sa.Column('id_direccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=255), nullable=False),
    sa.Column('numero_ext', sa.String(length=20), nullable=True),
    sa.Column('numero_int', sa.String(length=20), nullable=True),
    sa.Column('colonia', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('numero_telefonico', sa.String(length=20), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_table('emprendedora',
    sa.Column('id_emprendedora', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('descripcion_negocio', sa.Text(), nullable=True),
    sa.Column('estado_verificacion', sa.Enum('pendiente', 'verificada', 'suspendida', name='estadoverificacionenum'), nullable=False),
    sa.Column('insignia_hecho_juarez', sa.Boolean(), nullable=False),
    sa.Column('solicitud_insignia_activa', sa.Boolean(), nullable=False),
    sa.Column('enlace_redes_sociales', sa.JSON(), nullable=False),
    sa.Column('color_emprendedora_hex', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_emprendedora'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('reporte',
    sa.Column('id_reporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_reportador', sa.Integer(), nullable=False),
    sa.Column('tipo_contenido', sa.Enum('producto', 'servicio', 'resena', 'vendedora', name='tipocontenidoreporteenum'), nullable=False),
    sa.Column('id_referencia', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'resuelto', 'descartado', name='estadoreporteenum'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_reportador'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    op.create_table('pagina_emprendimiento',
    sa.Column('id_pagina', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_emprendedora', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.JSON(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_emprendedora'], ['emprendedora.id_emprendedora'], ),
    sa.PrimaryKeyConstraint('id_pagina'),
    sa.UniqueConstraint('id_emprendedora')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_emprendedora', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmado', 'enviado', 'entregado', 'cancelado', name='estadopedidoenum'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('stripe', 'paypal', 'mercadopago_spei', name='metodopagoenum'), nullable=False),
    sa.Column('id_direccion_envio', sa.Integer(), nullable=True),
    sa.Column('numero_rastreo', sa.String(length=200), nullable=True),
    sa.Column('codigo_qr_url', sa.String(length=500), nullable=True),
    sa.Column('proveedor_payment_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_direccion_envio'], ['direccion.id_direccion'], ),
    sa.ForeignKeyConstraint(['id_emprendedora'], ['emprendedora.id_emprendedora'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_emprendedora', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_stock', sa.Integer(), nullable=False),
    sa.Column('tipo_entrega', sa.Enum('envio', 'fisica', 'ambas', name='tipoentregaenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_emprendedora'], ['emprendedora.id_emprendedora'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('resena',
    sa.Column('id_resena', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_emprendedora', sa.Integer(), nullable=False),
    sa.Column('tipo_resena', sa.Enum('producto', 'servicio', name='tiporesenaenum'), nullable=False),
    sa.Column('id_referencia', sa.Integer(), nullable=False),
    sa.Column('calificacion_item', sa.Integer(), nullable=False),
    sa.Column('calificacion_vendedora', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=300), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_emprendedora'], ['emprendedora.id_emprendedora'], ),
    sa.PrimaryKeyConstraint('id_resena')
    )
    op.create_table('servicio',
    sa.Column('id_servicio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_emprendedora', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('enlace_reservacion', sa.String(length=500), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_emprendedora'], ['emprendedora.id_emprendedora'], ),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_table('atributo_producto',
    sa.Column('id_atributo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('talla', 'color', 'tamanio', 'material', name='tipoatributoenum'), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=False),
    sa.Column('atributo_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_atributo')
    )
    op.create_table('imagen_producto',
    sa.Column('id_imagen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('item_carrito',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo_entrega_seleccionado', sa.Enum('envio', 'fisica', name='tipoentregaitemenum'), nullable=True),
    sa.ForeignKeyConstraint(['id_carrito'], ['carrito.id_carrito'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_table('item_pedido',
    sa.Column('id_item_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=200), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo_entrega', sa.Enum('envio', 'fisica', name='tipoentregaitemenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item_pedido')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pedido')
    op.drop_table('item_carrito')
    op.drop_table('imagen_producto')
    op.drop_table('atributo_producto')
    op.drop_table('servicio')
    op.drop_table('resena')
    op.drop_table('producto')
    op.drop_table('pedido')
    op.drop_table('pagina_emprendimiento')
    op.drop_table('reporte')
    op.drop_table('emprendedora')
    op.drop_table('direccion')
    op.drop_table('carrito')
    op.drop_table('usuario')
    op.drop_table('categoria')
    # ### end Alembic commands ###
