"""Migracion de la BD con nuevo campo de image_url

Revision ID: 5df12abed55b
Revises: 6de94239106b
Create Date: 2026-04-09 03:31:32.056251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df12abed55b'
down_revision: Union[str, Sequence[str], None] = '6de94239106b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_pedido', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_pedido', 'imagen_url')
    # ### end Alembic commands ###
