"""Quinta migracion de la BD

Revision ID: 6de94239106b
Revises: 5413b34c6f54
Create Date: 2026-04-07 00:56:32.640977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de94239106b'
down_revision: Union[str, Sequence[str], None] = '5413b34c6f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagina_emprendimiento', sa.Column('visitas', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagina_emprendimiento', 'visitas')
    # ### end Alembic commands ###
